[package]
name = "cores"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
modular-bitfield = "0.11"
serde = { version = "1.0.219", features = ["derive"] }
charming = "0.4.0"
fxhash = "0.2.1"


[lib]
name = "cores"
path = "src/lib.rs"
