name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libcairo2-dev libatk1.0-dev libgdk-pixbuf2.0-dev libpango1.0-dev
        sudo apt-get install -y libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
        sudo apt-get install -y libxkbcommon-dev libxcb-shape0-dev libxcb-xfixes0-dev
        # Try to install WebKit2GTK (both versions for compatibility)
        sudo apt-get install -y libwebkit2gtk-4.1-dev || sudo apt-get install -y libwebkit2gtk-4.0-dev
        sudo apt-get install -y libglib2.0-dev pkg-config libgdk-3-dev
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      
    - name: Build cores crate only
      run: cargo build -p cores --verbose
      
    - name: Run core tests
      run: cargo test -p cores --verbose
      
    - name: Build GUI (may be skipped)
      run: cargo build -p gui --verbose
      continue-on-error: true
